### ISSUE TITLE
Include Visual Studio project files

### ISSUE THREAD

**Issue by FreeTheTech101** [twizre/iw4lan#7]
For easier building as well as no longer relying on the build PC to have LUA installed

**Comment by win32re** [comment]
You don't need lua, just download the latest premake5 nightly build from [here]
(http://sourceforge.net/projects/premake/files/Premake/nightlies/premake-dev-windows.zip/download) and extract premake5.exe to the directory you cloned this repository to.

Open a command prompt, cd to iw4lan dir and run 'premake5 vs2012' (a crash is present under vs2013 due to HiddenAssets/PatchMW2_Experimental code)
